services:
  # Servicio inestable que simula fallos, lentitud y publica eventos
  unreliable-service:
    image: node:22
    container_name: unreliable-service
    working_dir: /app
    volumes:
      - ./unreliable-service:/app
    command: bash -c "npm install express amqplib && node index.js"
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - rabbitmq

  # Servicio cliente que aplica patrones de resiliencia y consume mensajes
  client-service:
    image: node:22
    container_name: client-service
    working_dir: /app
    volumes:
      - ./client-service:/app
    command: bash -c "npm install express axios opossum amqplib && node index.js"
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=development
      - RABBITMQ_URL=amqp://rabbitmq
      - UNRELIABLE_URL=http://unreliable-service:4000
    depends_on:
      - unreliable-service
      - rabbitmq

  # Broker RabbitMQ con interfaz web (15672)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"